package com.halo.demo.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.tno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.tname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.tpassword
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String tpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.tno
     *
     * @return the value of tuser.tno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.tno
     *
     * @param tno the value for tuser.tno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.tname
     *
     * @return the value of tuser.tname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.tname
     *
     * @param tname the value for tuser.tname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.tpassword
     *
     * @return the value of tuser.tpassword
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getTpassword() {
        return tpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.tpassword
     *
     * @param tpassword the value for tuser.tpassword
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setTpassword(String tpassword) {
        this.tpassword = tpassword == null ? null : tpassword.trim();
    }
}
