package com.halo.demo.mapper;

import com.halo.demo.model.Admin;
import com.halo.demo.model.AdminExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    long countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int deleteByPrimaryKey(Integer tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    List<Admin> selectByExampleWithRowbounds(AdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     * @param example
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    Admin selectByPrimaryKey(Integer tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByPrimaryKey(Admin record);
}